---
permalink: install-linux/task_download_unified_manager.html 
sidebar: sidebar 
keywords: download, Unified Manager 
summary: '您必须从NetApp支持站点下载Unified Manager `.zip`文件才能安装Unified Manager。' 
---
= 正在下载 Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须从NetApp支持站点下载Unified Manager `.zip`文件才能安装Unified Manager。

* 您需要的内容 *

您必须具有 NetApp 支持站点的登录凭据。

您可以为 Red Hat Enterprise Linux 和 CentOS 系统下载相同的 Unified Manager 安装包。

.步骤
. 登录到 NetApp 支持站点，然后导航到 Unified Manager 的 Download 页面：
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetApp 支持站点"]

. 选择所需的 Unified Manager 版本并接受最终用户许可协议（ EULA ）。
. 下载适用于Linux的Unified Manager安装程序文件、并将该文件保存 `.zip`到目标系统上的目录中。
+
[NOTE]
====
** 确保为 Red Hat Enterprise Linux 系统下载正确版本的安装程序文件。根据您安装的是Red Hat Enterprise Linux 7还是8、请确保下载适当版本的Unified Manager `.zip`文件。
** NetApp建议您将代码签名证书(`.pem`()和数字签名)(`.sig`与文件一起 `.zip`下载。


====
. 验证已下载软件的校验和是否完整性。
. 如果您已下载代码签名证书和数字签名、则可以验证安装程序文件的完整性。您可以使用以下命令验证安装程序文件的完整性：
+
** 此命令将使用代码签名证书中的公有 密钥创建一个文件：
+
[listing]
----
openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>
----
+
*** 其中* AIQUM-RHEL-client-inter-root.pem*是包含代码签名证书的文件。


** 此命令用于验证安装程序文件上的签名：
+
[listing]
----
openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip
----
+
类似的消息 `Verified Ok`用于确认安装程序文件可以安全使用。




